### PR TITLE
Reorganized code for better module interface

### PR DESCRIPTION
**Pull request by dccarmo**
I was having issues using the module in my project and found the issue. Just reorganized code to make it readable by external sources.

### CODE REVIEW

**Comment by madsleejensen** [comment]
Hey @dccarmo thanks for the PR, can you explain what issues you had, and how this resolves it ?

**Comment by dccarmo** [comment]
The main issue I was having is that TypeScript wasn't able to find the module. My guess was that the module was missing an unique entry point, which is what I did and, it worked. So I decided to create this PR which might help more people.

**Comment by madsleejensen** [comment]
will try to run a test later this week :) just to ensure nothing will break!

**Comment by madsleejensen** [comment]
seems legit :) thanks alot for your help!

**Comment by dccarmo** [comment]
No problem!

**Pull request merged**
